CREATE TABLE estatisticas_jogadores (
    id SERIAL PRIMARY KEY,
    nome_jogador TEXT,
    time TEXT,
    id_time INTEGER REFERENCES times_brasileiros(id),
    numeracao INTEGER,
    nacao TEXT,
    posicao TEXT,
    idade INTEGER,
    gols INTEGER,
    assistencias INTEGER,
    cartoes_amarelos INTEGER,
    cartoes_vermelhos INTEGER,
    contatos NUMERIC,
    divididas NUMERIC,
    cortes INTEGER,
    bloqueios NUMERIC,
    xg NUMERIC,
    xag NUMERIC,
    passes_completos NUMERIC,
    passes_tentados NUMERIC,
    precisao_passes INTEGER,
    conducoes NUMERIC,
    data DATE
);
